# Generated by Django 3.2.11 on 2022-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhoIsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('registrant_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WhoIsDataHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whois_data', models.ManyToManyField(blank=True, to='services.WhoIsData')),
            ],
        ),
    ]
