# Generated by Django 3.2.11 on 2022-01-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoisdata',
            name='company_name',
        ),
    ]
